const ORDER_STATUS = {
  PENDING:    'PENDING',
  CONFIRMED:  'CONFIRMED',
  PROCESSING: 'PROCESSING',
  SHIPPED:    'SHIPPED',
  DELIVERED:  'DELIVERED',
  CANCELLED:  'CANCELLED',
  REFUNDED:   'REFUNDED',
};

const PAYMENT_STATUS = {
  PENDING:  'PENDING',
  PAID:     'PAID',
  FAILED:   'FAILED',
  REFUNDED: 'REFUNDED',
};

const PAYMENT_METHOD = {
  RAZORPAY: 'RAZORPAY',
  COD:      'COD',
};

const USER_ROLE = {
  CUSTOMER: 'CUSTOMER',
  ADMIN:    'ADMIN',
};

module.exports = { ORDER_STATUS, PAYMENT_STATUS, PAYMENT_METHOD, USER_ROLE };
